### ISSUE TITLE
No sound (Solved)

### ISSUE THREAD

**Issue by msh2050** [Xtr126/androidx86-installer-qemu-linux#2]
the android has no sound 
I solved this by adding 
```             
   -device ich9-intel-hda,id=sound0,bus=pcie.0,addr=0x1b -device hda-duplex,id=sound0-codec0,bus=sound0.0,cad=0 \
   -global ICH9-LPC.disable_s3=1 -global ICH9-LPC.disable_s4=1\
```

and in [this link](https://askubuntu.com/questions/1314825/how-to-enable-sound-in-qemu)

**Comment by Xtr126** [comment]
Thank you for pointing out it. I will add reference to Bliss OS wiki for Audio.
